### ISSUE TITLE
Make icons and sound for Info, important and critical notifications configurable

### ISSUE THREAD

**Issue by reyem** [syphr42/liblametrictime-java#9]
Currently the icons and sound for 
```
public String notifyInfo(String message) throws NotificationCreationException;

public String notifyImportant(String message) throws NotificationCreationException;

public String notifyCritical(String message) throws NotificationCreationException;
```

are hardcoded. The method signatures are straight forward for this use cases. However, it might be desirable to adjust the icons and sounds of this notifications. To keep the simplicity of the method signatures I would suggest adding configuration options. As this does not naturally fit into LocalConfiguration nor CloudConfiguration I would suggest either to add it just to Configuration or to introduce a new NotificationConfiguration class.
Once this is done we can also expose it in the configuration for the lametric-binding

**Comment by syphr42** [comment]
Rather than create configuration options, I just created a new method that takes more parameters (the old methods are still there with default values). However, I also backed that new method with a lot of supporting bits to make it easier to get at icons and sounds. This should allow the OH binding to store an instance of Icon and Sound for each notification channel as well as message and sound repeat values.
